### ISSUE TITLE
Setup of package 'services' failed: Integration 'XXXX' not found.

### ISSUE THREAD

**Issue by marcinsalata** [ufozone/ha-zcs-mower#138]
I have a "Configuration warnings"
Setup of package 'services' failed: Integration 'update_now' not found.
Setup of package 'services' failed: Integration 'set_profile' not found.
Setup of package 'services' failed: Integration 'work_now' not found.
Setup of package 'services' failed: Integration 'work_for' not found.
Setup of package 'services' failed: Integration 'work_until' not found.
Setup of package 'services' failed: Integration 'border_cut' not found.
Setup of package 'services' failed: Integration 'charge_now' not found.
Setup of package 'services' failed: Integration 'charge_for' not found.
Setup of package 'services' failed: Integration 'charge_until' not found.
Setup of package 'services' failed: Integration 'trace_position' not found.
Setup of package 'services' failed: Integration 'keep_out' not found.
Setup of package 'services' failed: Integration 'custom_command' not found.

what does it mean — How to fix it pleeaseeee. help

**Comment by ufozone** [comment]
I am not familiar with these messages and do not know where they can occur.

There is simply too much information missing for me to be able to help you in any way:
- What version of the intefration has the issue?
- What was the last working version of the integration?
- What version of Home Assistant are you using?
- What type of installation are you running?
- Provide a clear and concise description of what the problem is.
- Describe the issue you are experiencing here
- Tell us what you were trying to do and what happened.
- Diagnostics information, concrete log excerpts
- ....
